[package]
name = "perf"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
serde = "1.0.118"
serde_json = "1.0.60"
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", default-features = false, features = ["json", "diesel_sqlite_pool", "serve", "tera_templates"] }
diesel = { version = "1.4.5", features = ["sqlite", "chrono"] }
libsqlite3-sys = { version = ">=0.8.0, <0.21.0", features = ["bundled"] }
chrono = { version = "0.4.19" }
octocrab = { version = "0.8.2" }
jwt = { version = "0.11.0", features = ["openssl"] }
hmac = "*"
sha2 = "*"
openssl ="*"